### ISSUE TITLE
Number Of Rows Selected In Footer Not Updated After AJAX Reload

### ISSUE THREAD

**Issue by OliverHrdz** [gyrocode/jquery-datatables-checkboxes#32]
I have a DataTable with server-side processing on.  After the user updates selected row(s), I call `datatables.ajax.reload(null, false)` to refresh the data displayed.

Depending on the server-side business logic, the row(s) that were selected prior to the update were either updated themselves, or new rows were created from them in the database, with different primary keys.  These keys are what I'm using for the checkbox column to uniquely identify each row.

The issue is that there are times after the data in the table reloads that the previously selected rows with certain IDs are no longer in the table, yet the footer will still display that there are rows selected.  I have to completely reload the entire page to get the footer to clear up with the correct count.

Besides a complete page reload, any other way to get the summary info in the footer to refresh after an AJAX reload of the DataTable?  Thanks!

**Comment by mpryvkin** [comment]
Thanks for reporting this, I think it is somewhat related to #26. I will work on finding the possible resolution.

**Comment by TOuhrouche** [comment]
Thanks for the awesome library! I am having the exact same issue where the table somehow remembers the previously selected rows. I tried to deselect all checkboxes after an ajax reload but that didn't work :(

**Comment by mpryvkin** [comment]
Are you using state saving with `stateSave: true` at all?

**Comment by TOuhrouche** [comment]
Nope, my settings are pretty simple (used the same from documentation)
Here is a simplified version of my settings.
```
       table = $("#my-table").DataTable({
            serverSide: true,
            ajax: {
                url: "/datapoint"
            },
            autoWidth: false,
            processing: true,
            searchDelay: 500,
            bLengthChange: false,
            deferRender: true,
            scroller: true,
            orderClasses: false,
            createdRow: renderNewRow,
            columns: [
                { "data": null},
                ...
            ],
            columnDefs: [{
                "targets": [0], // checkbox
                "visible": true,
                "searchable": false,
                "orderable": false,
                "checkboxes": {
                    "selectRow": true
                }
            },
           .....
           ],
            pageLength: 50,
            'order': [[1, 'asc']]
        });```

**Comment by mpryvkin** [comment]
Can you please the most recent version of the code? I believe the issue has been resolved with [this commit](https://github.com/gyrocode/jquery-datatables-checkboxes/commit/d9a9c2e3a066476f35ef9f5fc7454a5b860184ed).

**Comment by TOuhrouche** [comment]
Thanks for the super quick reply. I upgraded to the latest dev version and the issues is gone. There is still a tiny glitch where the "selected rows footer" is still showing the old selection count.

**Comment by OliverHrdz** [comment]
I've tested the latest version, and the footer summary is now correct after the AJAX reload in my use case.

But, upon the initial display of my table, the checkboxes are not rendered in the first column.  I believe it has to do with my DataTable configured with `deferLoading: true`, which I set only because I'm converting an existing application from manually created tables, and frankly I was too lazy to modify the static html for the table.  :)

I changed my code to not defer loading and only use AJAX, and the initial display now shows the checkboxes.  This is very acceptable, I'll just have to change all my DataTables to not defer loading.

**Comment by mpryvkin** [comment]
Oliver, thanks for confirming that it works! I will test `deferLoading` option.

**Comment by mpryvkin** [comment]
Tahar,

I couldn't replicate the issue with `table.column(0).checkboxes.selected()`, see [this example](https://jsfiddle.net/snqw56dw/504/) where it works as expected. The issue is with your code where you use `data: null` for the first column. Instead you need to point to a data property containing unique values.

You also mention that the issues are gone, but then write that "selected rows" footer shows the old selection count which is contradictory to me.

**Comment by TOuhrouche** [comment]
Hi Michael,
👍 for the fast answer :)
I will try setting the data to something other than `null` and see how that flies :)

As for the selection, the table seems to go out of sync with the checkboxes extension where I select a set of items, perform some action will reload the table. When the table reloads (via ajax), the previously checked checkboxes get unchecked but the selected rows count at the bottom still shows the selection count I had earlier made. 
Maybe this is all related to the `data: null` settings? I will give it another go and report back as soon as possible.

**Comment by TOuhrouche** [comment]
Hi Michael,
Just made the suggested changed and it all works great! It was definitely the `data: null` settings which was causing all the issues. Again, thanks for the fantastic work.

**Comment by praditha** [comment]
Hi Michael,
Thanks for the great library.

> Are you using state saving with stateSave: true at all?

I have same problem here, and yes I'm using `stateSave: true`.
So I used the checkbox to select the row which will be deleted by system.
I used the server request to do the delete function, not Ajax request, so it will reload the page.
But after the rows was deleted and come back to the table page, the Number of Row Selected is not reset and still counting from the last selected row.

I've tried to remove manually from local storage, but it still not working.
```
var currentState = JSON.parse(localStorage.getItem("DataTables_vouchers-table_/en/admin/voucher"));
delete currentState['checkbox'];
localStorage.setItem("DataTables_vouchers-table_/en/admin/voucher", JSON.stringify(currentState));
```
